name: RTP_Tweaks
version: '1.0-SNAPSHOT'
main: me.sachin.rTP_Tweaks.RTP_Tweaks
api-version: '1.21'
depend: [BetterRTP]

commands:
  cinfo:
    description: Display information about your current cluster
    usage: /<command>
    permission: clusters.admin
    permission-message: You don't have permission to use this command!

permissions:
  clusters.admin:
    description: Allows access to cluster information commands
    default: op